# 应用名称
spring:
  application:
    name: encryption-spring-boot-sample
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'


# 应用服务 WEB 访问端口
server:
  port: 9000
  servlet:
    context-path: /encryption

# 加密配置
encryption:
  charset: 'UTF-8'
  algorithm: rsa_with_aes
  configs:
    secret-header-key: 'secret'
    public-key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5jqX3qcr0xHfYvb1xh7Th4BzOg8hFChgpp4Zcb1LTcIXiCN1FYFpZkMHbwtZzRY4M+ZLSMAKx3ExNc1XLAQsoErHIzt3RXr1PoOt+vN/YeV7r2D55LOJh3HJBT1xhf2B9Q/EAQfnYoMQ68o5NV34m3nMPtRFa5D01b9DD8i/xTAfUfWXKJ4XklFxoWQ6f3ltguZlqfsNeXdwmbcukm9NVY83/R8KJNtkelqMDYkEB0nPvM+Jxjp+BJ54Y6cG904V57Tswv/7OZg0AWOqt3TzLK3gBbpYINLIgxotwY0lFwz3NfJyYs9xmp4ZM3/+wlgbbGywz3K+9MDOziwN/vWuIwIDAQAB'
    private-key: 'MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDmOpfepyvTEd9i9vXGHtOHgHM6DyEUKGCmnhlxvUtNwheII3UVgWlmQwdvC1nNFjgz5ktIwArHcTE1zVcsBCygSscjO3dFevU+g636839h5XuvYPnks4mHcckFPXGF/YH1D8QBB+digxDryjk1Xfibecw+1EVrkPTVv0MPyL/FMB9R9ZconheSUXGhZDp/eW2C5mWp+w15d3CZty6Sb01Vjzf9Hwok22R6WowNiQQHSc+8z4nGOn4Ennhjpwb3ThXntOzC//s5mDQBY6q3dPMsreAFulgg0siDGi3BjSUXDPc18nJiz3Ganhkzf/7CWBtsbLDPcr70wM7OLA3+9a4jAgMBAAECggEABRDQ+qMvAavpAGJysfNHsDmRT3u5vJnO1puv76K8n29f2Sz+jISWbxuWdEkJpsuQXQP6MBWZpx3EeWyVOHC3EqfSjeHnE+5Kqx92moj1CpBkEk3N8cxJgGNuiuD5OHuFeoDoTSWBX9eGbcm7TINOzwz1A4TkKiO8X1+f+B7wqUQFHN7gzVzPp8bKlM/YnY9f7zR8/dXpi8fpu3hW1U75OF7nxZCxfEN6YvSbkzCLUuOqnTSLm4kx/A7QVD/wXZlv08AmFlD5l1k+G+uzzHi+5+LaZRKUCnAt0I3wzNDim1O4ytQs1q5Sh0cc5vDsxF4R8PyO3RPTVQ/r8x9JXaYgUQKBgQD3qUzDis92xg3vCPWbAQ2NRPklzpQw3rFhobTiRafRHXVegwOLKG7tQ95s6KAmgLY+UzkQATXg5XgFJ6b4S9xBCJvJN/o1k9+y+PlOVjMddnL7ZcOuA0nEMY2lj+mmAFul7TQGsndXFnjPwTXDpL+EvbFjChMSEkqiWmCVtrRpTQKBgQDt+wkbS9s6ymi6aSIH/NNJ8pQYCFWSzlqPnGPi6K+aKSqDHP+dWf03OYD/lGDJCFp9urD2BurHgbc/NNn01QWjqXzwr8KugsbNhRNrneBNnFpxmQtqYPVEGX4Wy2/Cg0iNjAiwEFwmTeKA05uXjrZb6N+L+LxGHS3qlJib+js9LwKBgA0b9AlBtruVvjUR51Y+FwaMSRfcOHHhx8fgNF/pyflCsuy+yJg8GqsKdaKUKa4AECV6aEHVnpF59AFp2Oe5tD3pA74B7YeafTPPA/tGiswbcfimqVXzrJrq+JFz7a0wxakhxig4mCKO+PQeSQdDGDQhilswtFO3jiXL3OLv2drdAoGACKRxNDiRAZWQMBTZU4ju82SH1EeZM/eiekyno/nnRqXwEUrgTYqTE4pXEPEGgsZ24tIA0y51IEGpsfXtZGLIDaV+EA+R9lxxc809Y08ccjUXY8C3FWnn/k0esx04Ncwmul03g41Ui1+QtjT5FYvtO3E9jQu/apxsqnQzBpcTx6kCgYB3HlWpJzevkl2m0I+YlxDHPR0ec/MBM/cr7x3ebjm+2sbYmPkza+AfclZ1mc5yxza/WDixLbsT3TrffYV7zKHP5Ggq0k5jZlIiVkU9GVUIb0BApyMNXCvEmV9esQcmIKzozxaC3EqhM0cy4j8Vi2j5CvZmlwMvBeOSHjeT+MSpTw=='
#    secret: 'ABCDEFGHIJKL0123'
    iv: '1234567890123456'

